apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  annotations:
    "helm.sh/hook": pre-install
  name: es-paulao-api-test-application
  namespace: paulao-api-test
spec:
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        #apenas simulando uma aplicação, deveria pegar secret da AWS relacionado ao serviço específico.
        key: fluentd-sre-poc-v8
  refreshInterval: 30s
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-cluster-secret-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: paulao-api-test-secrets