apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentd-aggregator
  namespace: fluentd
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::876897421480:role/will-dev-sre-poc-v8-service-account-addon-fluentd-role
