apiVersion: v1
data:
  prometheus-additional.yaml: {{ .Files.Get "additional-scrapes/additional-scrape-configs.yaml" | b64enc }}
kind: Secret
metadata:
  annotations:
    "helm.sh/hook": pre-install
  creationTimestamp: null
  name: additional-scrape-configs
  namespace: monitoring