apiVersion: v2
name: prometheus-community
description: A Helm chart for Kubernetes

type: application
version: 36.6.0
appVersion: "36.6.0"

dependencies:
  - name: kube-prometheus-stack
    version: 36.6.2
    repository: https://prometheus-community.github.io/helm-charts
  - name: grafana
    version: "6.32.*"
    repository: https://grafana.github.io/helm-charts
    condition: global.grafana.enabled

