apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  annotations:
    "helm.sh/hook": pre-install
  name: es-fluentd
  namespace: fluentd
spec:
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: fluentd-secret-test-sre
  refreshInterval: 30s
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-cluster-secret-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: fluentd-aggregator-secret