# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: paulo-api
#   namespace: paulo
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app.kubernetes.io/name: paulo-api
#   template:
#     metadata:
#       labels:
#         app.kubernetes.io/name: paulo-api
#     spec:
#       containers:
#         - name: paulo-api
#           envFrom:
#             - configMapRef:
#                 name: paulo-api-configmap
#                 optional: false
#             - secretRef:
#                 name: paulo-api-secrets
#                 optional: false        
#           image: >-
#             142401413602.dkr.ecr.sa-east-1.amazonaws.com/ecr-flask-api-example:paulo-teste-newrelic-c38a4679cf3337066c85d626c8d9305d5af72263
#           ports:
#             - name: http
#               containerPort: 8000
#               protocol: TCP
#           resources:
#             limits:
#               cpu: 500m
#               memory: 300Mi
#             requests:
#               cpu: 400m
#               memory: 200Mi
#           terminationMessagePath: /dev/termination-log
#           terminationMessagePolicy: File
#           imagePullPolicy: IfNotPresent
#       restartPolicy: Always
#       terminationGracePeriodSeconds: 30
#       serviceAccountName: paulo-api
#       serviceAccount: paulo-api
#       dnsPolicy: ClusterFirst
#       schedulerName: default-scheduler
#   strategy:
#     type: RollingUpdate
#     rollingUpdate:
#       maxUnavailable: 0
#       maxSurge: 1
#   revisionHistoryLimit: 10
#   progressDeadlineSeconds: 600

apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: paulo-api
  namespace: paulo
  labels:
    app.kubernetes.io/name: paulo-api
spec:
  replicas: 4
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {duration: 10}
      - setWeight: 40
      - pause: {duration: 10}
      - setWeight: 60
      - pause: {duration: 10}
      - setWeight: 80
      - pause: {duration: 10}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: paulo-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: paulo-api
    spec:
      containers:
      - name: paulo-api
        envFrom:
          - configMapRef:
              name: paulo-api-configmap
              optional: false
          - secretRef:
              name: paulo-api-secrets
              optional: false        
        image: >-
          142401413602.dkr.ecr.sa-east-1.amazonaws.com/ecr-flask-api-example:paulo-teste-newrelic-e9ed135cb8313ce1b2aa672c1406bafb2ff1beac
        ports:
          - name: http
            containerPort: 8000
            protocol: TCP
        resources:
          limits:
            cpu: 200m
            memory: 300Mi
          requests:
            cpu: 150m
            memory: 200Mi
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
      serviceAccountName: paulo-api
      serviceAccount: paulo-api
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler