- job_name: 'fluentd'
  static_configs:
    - targets: ['fluentd-aggregator-prometheus-service.fluentd.svc.cluster.local:24231']

- job_name: 'core-pix-api-gateway'
  scrape_interval: 3s
  metrics_path: '/metrics'
  static_configs:
    - targets: ['core-pix-api-gateway.core-pix-api-gateway.svc.cluster.local:8000']

- job_name: 'istiod'
  kubernetes_sd_configs:
  - role: endpoints
    namespaces:
      names:
      - istio-system
  relabel_configs:
  - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
    action: keep
    regex: istiod;http-monitoring
  scheme: https
  tls_config:
    ca_file: /etc/prom-certs/root-cert.pem
    cert_file: /etc/prom-certs/cert-chain.pem
    key_file: /etc/prom-certs/key.pem

- job_name: 'envoy-stats'
  metrics_path: /stats/prometheus
  kubernetes_sd_configs:
  - role: pod

  relabel_configs:
  - source_labels: [__meta_kubernetes_pod_container_port_name]
    action: keep
    regex: '.*-envoy-prom'    
  scheme: https