apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: maykol-canary
  namespace: argocd
spec:
  destination:
    namespace: maykol-canary
    server: https://kubernetes.default.svc
  ignoreDifferences:
    - group: argoproj.io/v1alpha1
      jsonPointers:
        - /spec/replicas
      kind: Rollout
      name: maykol-canary
      namespace: maykol-api-test
  project: tribe-applications
  source:
    path: tribe/tribe-apps-manifests/maykol-canary
    repoURL: https://github.com/ayrtonscoelho/terraform-modules.git
    targetRevision: refactoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m0s
      limit: 5
    syncOptions:
      - CreateNamespace=false
      - ApplyOutOfSyncOnly=true