apiVersion: external-secrets.io/v1alpha1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.clusterSecretStore.name }} 
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.clusterSecretStore.awsRegion }}
      auth: { .Values.clusterSecretStore.awsAuth }