apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example
spec:
  refreshInterval: 1h           # rate SecretManager pulls Azure Key Vault
  secretStoreRef:
    kind: SecretStore
    name: example               # name of the SecretStore (or kind specified)
  target:
    name: secret-to-be-created  # name of the k8s Secret to be created
    creationPolicy: Owner
  dataFrom:
  - find:
      name:
        regexp: "^example"
  - find:
      tags:
        author: seb
        environment: dev
  # secret value is in JSON format and we unmarshall it into multiple key/values in k8s secret
  - extract: 
      key: test
  # get all tags and the tags in JSON format will be unmarshall 
  - extract: 
      key: test
      metadataPolicy: Fetch