global:
  cluster: will-dev-sre-poc-v8
  lowDataMode: true
  customSecretName: newrelic-license-key
  customSecretLicenseKey: new-relic-secret-test-sre

newrelic-infrastructure:
  privileged: true
 
ksm:
  enabled: true
  
kubeEvents:
  enabled: true

newrelic-pixie: 
  enabled: false
  apiKey: px-api-f160bbb0-df25-454e-9aae-07c6340d0401

pixie-chart:
  enabled: false
  deployKey: px-dep-99ad86c1-1a04-42b1-9806-eff14b139d8b
  clusterName: will-dev-sre-poc-v8