global:
  licenseKey: 13386b5ec2f6f690ade4896648d25eb79b02NRAL
  cluster: will-dev-sre-poc-v2
kubeEvents:
  enabled: true
webhook:
  enabled: true
prometheus:
  enabled: true
logging:
  enabled: true
ksm:
  enabled: true