global:
  cluster: will-dev-sre-poc-v7
  lowDataMode: true
  customSecretName: newrelic-license-key
  customSecretLicenseKey: licenseKey

newrelic-infrastructure:
  privileged: true
 
ksm:
  enabled: true
  
kubeEvents:
  enabled: true