apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: will-default
  annotations:
    "helm.sh/hook": post-install
spec:
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["on-demand", "spot"]
    - key: "node.kubernetes.io/instance-type"
      operator: In
      # values: ["t3.large", "t3.xlarge", "t3.2xlarge", "t3a.large", "t3a.xlarge", "t3a.2xlarge"]
      values: ["t3.xlarge", "t3.2xlarge", "t3a.large", "t3a.xlarge", "t3a.2xlarge"]
    - key: "topology.kubernetes.io/zone"
      operator: In
      values: ["us-east-1a", "us-east-1b", "us-east-1c"]
  limits:
    resources:
      cpu: 500
      memory: 500Gi
  providerRef:
    name: will-default
  ttlSecondsAfterEmpty: 900
  ttlSecondsUntilExpired: 2592000