# Default values for external-dns.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: k8s.gcr.io/external-dns/external-dns
  # Overrides the image tag whose default is v{{ .Chart.AppVersion }}
  tag: ""
  pullPolicy: IfNotPresent

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

commonLabels: {}

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations:
  # The name of the service account to use.
    eks.amazonaws.com/role-arn: "arn:aws:iam::607150308374:role/external-dns-test-sre"
  name: "external-dns"

rbac:
  # Specifies whether RBAC resources should be created
  create: true
  additionalPermissions: []

# Annotations to add to the Deployment
deploymentAnnotations: {}

podLabels: {}

# Annotations to add to the Pod
podAnnotations: {}

shareProcessNamespace: false

podSecurityContext:
  fsGroup: 65534

securityContext:
  runAsNonRoot: true
  runAsUser: 65534
  readOnlyRootFilesystem: true
  capabilities:
    drop: ["ALL"]

priorityClassName: ""

terminationGracePeriodSeconds:

serviceMonitor:
  enabled: false
  additionalLabels: {}
  interval: 1m
  scrapeTimeout: 10s


livenessProbe:
  httpGet:
    path: /healthz
    port: http
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 2
  successThreshold: 1

readinessProbe:
  httpGet:
    path: /healthz
    port: http
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

service:
  port: 7979
  annotations: {}

extraVolumes: []

extraVolumeMounts: []

resources:
  limits:
    cpu: 50m
    memory: 150Mi
  requests:
    cpu: 25m
    memory: 100Mi   

nodeSelector: {}

tolerations: []

affinity: {}

topologySpreadConstraints: []

logLevel: debug
logFormat: text

interval: 1m
triggerLoopOnEvent: false

sources:
  - ingress

policy: upsert-only

registry: txt
txtOwnerId: Z0606217KFJ9VW7JD937
#txtPrefix: ""
#txtSuffix: ""


domainFilters: 
  - "will-dev.local"

provider: aws

