apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    istio-injection: enabled
    sidecar.jaegertracing.io/inject: "true"
  name: maykol-api
spec: {}