configuration:
  backupStorageLocation:
    bucket: will-dev-sre-poc-v8-velero
  provider: aws
  volumeSnapshotLocation:
    config:
      region: us-east-1
credentials:
  useSecret: false
initContainers:
- name: velero-plugin-for-aws
  image: velero/velero-plugin-for-aws:v1.2.0
  volumeMounts:
  - mountPath: /target
    name: plugins
serviceAccount:
  server:
    annotations:
      eks.amazonaws.com/role-arn: "arn:aws:iam::876897421480:role/eks-velero-backup"
