apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: error-rate
spec:
  metrics:
  - name: error-rate
    interval: 5m
    successCondition: len(result) == 0 || result[0] > 0.95
    #successCondition: result[0] <= 0.95
    failureLimit: 3
    provider:
      prometheus:
        address: http://prometheus-server.monitoring
        query: |
          sum(irate(
            istio_requests_total{reporter="source",destination_service=~"{{maykol-sre.owill.com.br}}",response_code=~"5.*"}[5m]
          )) /
          sum(irate(
            istio_requests_total{reporter="source",destination_service=~"{{maykol-sre.owill.com.br}}"}[5m]
          ))