apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: maykol-api-error-rate
spec:
  metrics:
  - name: error-rate
    interval: 30s
    #successCondition: len(result) == 0 || result[0] > 0.95
    failureCondition: result[0] >= 0.10
    failureLimit: 2
    provider:
      prometheus:
        address: http://prometheus-server.monitoring
        query: |
          sum(
              irate(istio_requests_total{destination_service_name="maykol-api-service",response_code="500"}[5m]
          )) /
          sum(
              irate(istio_requests_total{destination_service_name="maykol-api-service",response_code="200"}[5m]
          ))

# apiVersion: argoproj.io/v1alpha1
# kind: AnalysisTemplate
# metadata:
#   name: success-rate
# spec:
#   # args:
#   # - name: rollout-ref-deployment.maykol-api:80
#   metrics:
#   - name: success-rate
#     interval: 5m
#     # NOTE: prometheus queries return results in the form of a vector.
#     # So it is common to access the index 0 of the returned array to obtain the value
#     successCondition: len(result) == 0 || result[0] > 0.95 #result[0] >= 0.95
#     failureLimit: 3
#     provider:
#       prometheus:
#         address: http://prometheus-server.monitoring
#         query: |
#           sum(irate(
#             istio_requests_total{reporter="source",destination_service=~"maykol-sre.owill.com.br/",response_code!~"5.*"}[5m]
#           )) /
#           sum(irate(
#             istio_requests_total{reporter="source",destination_service=~"maykol-sre.owill.com.br/"}[5m]
#           ))