kind: Service
apiVersion: v1
metadata:
  name: rollout-ref-deployment
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: "8080"
spec:
  selector:
    app: rollout-ref-deployment
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080