apiVersion: v1
kind: Namespace
metadata:
  annotations:
    "helm.sh/hook": pre-install
  name: istio-system
  labels:
    istio-injection: enabled
spec: {}
---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    "helm.sh/hook": pre-install
  name: kong-istio
  labels:
    istio-injection: enabled
spec: {}