apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  annotations:
  name: es-api-key
  namespace: newrelic
spec:
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: will-dev-sre-poc-v7-secret-argocd-admin
  refreshInterval: 30s
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-cluster-secret-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: newrelic-api-key