apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paulao-api-test-pvc
  namespace:  paulao-api-test
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: gp3
  resources:
    requests:
      storage: 30Gi
