apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: paulao-api-test
  namespace: paulao-api-test
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    app.kubernetes.io/name: paulao-api-test
spec:
  replicas: 8
  workloadRef:
    apiVersion: apps/v1
    kind: Deployment
    name: paulao-api-test
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause:
            duration: 60
        - setWeight: 40
        - pause:
            duration: 60
        - setWeight: 60
        - pause:
            duration: 60
        - setWeight: 80
        - pause:
            duration: 60